### ISSUE TITLE
No module named 'cffi'

### ISSUE THREAD

**Issue by idan89** [strongswan/strongMan#103] opened 2018-05-24 06:00 UTC
Hey there, 
When executing the setup.py I get the following error:

$ sudo ./setup.py install
Start strongMan installation
	- Virualenv
	- Requirements
	- Database migration
		Delete strongMan/db.sqlite3
[Errno 2] No such file or directory: '/home/USER/strongMan/strongMan/db.sqlite3'
Traceback (most recent call last):
  File "/home/USER/strongMan/env/lib/python3.6/site-packages/oscrypto/_openssl/_libcrypto_cffi.py", line 11, in <module>
    from cffi import FFI
ModuleNotFoundError: No module named 'cffi'
...

Can you help me?
Thank you in advance!

**Comment by tobiasbrunner** [comment] 2018-05-24 06:45
I don't think the problem is what you referred to in the title, but this:

    Traceback (most recent call last):
      File "/home/USER/strongMan/env/lib/python3.6/site-packages/oscrypto/_openssl/_libcrypto_cffi.py", line 11, in 
        from cffi import FFI
    ModuleNotFoundError: No module named 'cffi'

Might be an issue with LibreSSL, see wbond/oscrypto#18. Unfortunately, the latest release of _oscrypto_ is from last December so the fix for this hasn't been released yet.

**Comment by twmbx** [comment] 2018-10-16 14:38
I'm having this same problem on Ubuntu 16.04, @idan89 did you find a way to resolve this?

**Comment by twmbx** [comment] 2018-10-16 14:57
@tobiasbrunner I just updated dependencies for oscrypto and asn1crypto in requirements.txt to
    `oscrypto==0.19.1`
    `asn1crypto==0.22.0`
and that allowed me to complete an installation. not sure if this would suitable for a PR or if it would intro problems, haven't tested strongMan as yet... let me know and I'll submit the pr though.

cc: @idan89

**Comment by tobiasbrunner** [comment] 2018-10-17 07:48
Are you sure you had the same problem? Because 0.19.1 is the version I mentioned above, from last Decemeber, that doesn't include the fix for that dependency issue (also see https://github.com/wbond/oscrypto/issues/18#issuecomment-428976699).

**Comment by slokhorst** [comment] 2018-11-25 14:00
@twmbx's solution also fixes it for me. Apparently our issue is caused by a different bug which *is* fixed in 0.19.1.

Any reason not to require `0.19.1` in `requirements.txt`?

**Comment by tobiasbrunner** [comment] 2018-11-29 15:52
> Any reason not to require `0.19.1` in `requirements.txt`?

Not really, but this also requires some updates to the private key loader and unit tests. I pushed a few commits to the _crypto-update_ branch. Let me know if that works for you.

**Comment by slokhorst** [comment] 2018-11-29 19:46
The *crypto-update* branch works for me. Thanks!

**Comment by tobiasbrunner** [comment] 2018-11-30 11:09
Thanks for testing. I pushed the patches to _master_ and will close the issue for now.

**Closed by tobiasbrunner** 2018-11-30 11:09 UTC
