### ISSUE TITLE
[Error 2] In settingUp strongMan

### ISSUE THREAD

**Issue by SonnyMargwe** [strongswan/strongMan#138] opened 2022-09-05 07:58 UTC
python setup.py install
Start strongMan installation
	- Virtualenv
	- Requirements
	- Database migration
		Delete strongMan/db.sqlite3
[Errno 2] No such file or directory: '/home/USER/strongMan/strongMan/db.sqlite3'
	- Static files

**Comment by tobiasbrunner** [comment] 2022-09-05 08:22
This is a duplicate of #133.

**Closed by tobiasbrunner** 2022-09-05 08:22 UTC
